services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8082:8082 # qbit
      - 6881:6881 # qbit
      - 6881:6881/udp # qbit
    volumes:
      - ${VOLUME_PATH}/config/gluetun:/gluetun
    networks:
      - traefik-network
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - VPN_ENDPOINT_IP=${VPN_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=${VPN_ENDPOINT_PORT}
      - DNS_ADDRESS=${DNS_ADDRESS}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.rule=Host(`${QBITTORRENT_SUB_DOMAIN}.${SERVER_DOMAIN}`)
      - traefik.http.routers.qbittorrent.entrypoints=websecure
      - traefik.http.routers.qbittorrent.service=qbittorrent
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8082
    security_opt:
      - no-new-privileges:true

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8082
      - UMASK=022
    volumes:
      - ${VOLUME_PATH}/config/qbittorrent:/config
      - ${VOLUME_PATH}/downloads:/downloads
    healthcheck:
      test: curl google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - autoheal=true
      - homepage.group=Media
      - homepage.name=qBittorrent
      - homepage.icon=qbittorrent
      - homepage.href=${URL_SCHEME}://${QBITTORRENT_SUB_DOMAIN}.${SERVER_DOMAIN}
      - homepage.description=P2P BitTorrent client
      - homepage.widget.type=qbittorrent
      - homepage.widget.url=${URL_SCHEME}://${QBITTORRENT_SUB_DOMAIN}.${SERVER_DOMAIN}
      - homepage.widget.fields=["leech", "download", "seed", "upload"]

  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOLUME_PATH}/config/jellyfin:/config
      - ${VOLUME_PATH}/complete/tv:/data/tvshows
      - ${VOLUME_PATH}/complete/movies:/data/movies
    ports:
      - 8096:8096
    networks:
      - traefik-network
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_SUB_DOMAIN}.${SERVER_DOMAIN}`)
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin
      - homepage.href=${URL_SCHEME}://${JELLYFIN_SUB_DOMAIN}.${SERVER_DOMAIN}
      - homepage.description=Watch movies and TV shows.
      - homepage.widget.type=jellyfin
      - homepage.widget.url=${URL_SCHEME}://${JELLYFIN_SUB_DOMAIN}.${SERVER_DOMAIN}
      - homepage.widget.key=${JELLYFIN_API_KEY}
      - homepage.widget.enableBlocks=true
      - homepage.widget.enableNowPlaying=true
    security_opt:
      - no-new-privileges:true

networks:
  traefik-network:
    external: true
